#!/bin/bash
hosts=(gcp10 gcp20 gcp30 gcp40 gcp50 gcp60 gcp70 gcp80)
zones=(us-west1-b us-west1-a us-east1-c us-east1-d us-central1-b us-central1-c asia-east1-c asia-east1-a)

files="/tmp/log*.png /tmp/log*.rooms /tmp/log*.yaml"
cd /var/www/html
while true 
do
  echo "[`export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S`] START copy files from compute instances"
  for (( i = 0; i < ${#hosts[@]]}; ++i ))
  do
    host=${hosts[$i]}
    zone=${zones[$i]}
    gcloud compute copy-files $host:"$files" . --zone $zone
  done

  gen-html *.rooms > 00index.html
  grep "1" *.rooms > 00ROOMS

  echo "[`export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S`] END   copy files from compute instances"

  sleep 600
done

