#!/bin/bash
hosts=(gcp10 gcp20 gcp30 gcp40 gcp50 gcp60 gcp70 gcp80)
zones=(us-west1-b us-west1-a us-east1-c us-east1-d us-central1-b us-central1-c asia-east1-c asia-east1-a)

while true 
do
  echo "*** check status of compute instances and start if not RUNNING ***"
  for (( i = 0; i < ${#hosts[@]]}; ++i ))
  do
    host=${hosts[$i]}
    zone=${zones[$i]}
    status=`gcloud compute instances describe $host --zone $zone | grep status`
    echo -n "[`export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S`] $host $status"
    if [ "$status" = "status: RUNNING" ]; then
      echo " => OK"
    else
      if [ "$status" = "status: STOPPING" ]; then
        echo -n " => wait 20sec"
        sleep 20
      fi
      echo " => NG => try to start it"
      gcloud compute instances start $host --zone $zone
      status=`gcloud compute instances describe $host --zone $zone | grep status`
      echo  "[`export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S`] $host $status"
      echo " => OK"
    fi
  done
  sleep 120
done

