#!/bin/bash -x
# usage: all-plot log-file1 log-file2 ...

files=($*)
# need to adjust location of file plot2.py in following line
plot="python $HOME/tensorflow/EXPERIMENT3/plot2.py -n 60 --sx=5 --sy=5 --save -er 99 "

for (( i = 0; i < ${#files[@]}; ++i ))
do
    f=${files[$i]}
    sleep 5; $plot -i r     $f &
    sleep 5; $plot -i lives $f &
    sleep 5; $plot -i s     $f &
    sleep 5; $plot -i tes   $f &
    sleep 5; $plot -i RO    $f &
    sleep 5; $plot -i v     $f &
    sleep 5; $plot -i pr    $f &
    sleep 5; $plot -i k     $f &
    sleep 5; $plot -i R     $f &
done

