#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 directory"
    exit 1
fi

if [ ! -e $1 ]; then
    echo "$1: not exist"
    exit 1
fi

cd $1
for f in psc.*; do
  echo "@@@ convert $f"
  python ../psc-view.py $f --save
done
