#!/bin/sh -x

if [ $# -ne 1 ]; then
    echo "Usage: $0 directory"
    exit 1
fi

if [ ! -e $1 ]; then
    echo "$1: not exist"
    exit 1
fi

if [ ! -d $1 ]; then
    echo "$1: is not directory"
    exit 1
fi

while true
do
  echo "@@@@@ `export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S` @@@@@"
  export TZ=JST-9;date +%Y/%m/%d-%H:%M:%S
  run-avconv-all $1
  run-avconv-all $1
  rm -r $1/*RM??
  sleep 300
done
