DQN-M:
	python DQN-gym-train.py -g 0 -e MontezumaRevenge-v0 --double f --dueling t --logdir MontezumaRevenge-v0-DQN

DQN-P:
	python DQN-gym-train.py -g 0 -e Pitfall-v0 --double f --dueling t --logdir Pitfall-v0-DQN


